name: test-expressions
on: [push]
jobs:
  test-expressions-literals:
    name: test-expressions-literals
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event }}
  test-expressions-functions:
    runs-on: ubuntu-latest
    steps:
      env:
        xx: format('{{Hello {0} {1} {2}!}}', 'Mona', 'the', 'Octocat')
        yy: join(github.event.issue.labels.*.name, ', ')
      - run: echo $xx
      - run: echo $yy